apiVersion: v1
kind: Pod
metadata:
  name: pod-base
  namespace: dev
  labels:
    version: "1.0"
spec:
  containers:
    - name: nginx
      image: nginx
    - name: busybox
      image: busybox
      command: ["/bin/sh" "-c" "while true; do /bin/echo $(date +%T)>>/tmp/hello.txt;sleep 3;done;"]