apiVersion: v1
kind: Namespace
metadata:
  name: host-dev

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: host-path
  namespace: host-dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-host
  template:
    metadata:
      labels:
        app: nginx-host
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
              hostPort: 80
          volumeMounts:
            - mountPath: /var/log/nginx
              name: log-volume
        - name: busybox
          image: busybox:1.30
          command: ["/bin/sh","-c","tail -f /logs/access.log"]
          volumeMounts:
            - mountPath: /logs
              name: log-volume
      volumes:
        - name: log-volume
          hostPath:
            path: /opt/log/nginx
            type: DirectoryOrCreate