apiVersion: v1
kind: Service
metadata:
  name: node-service
  namespace: dep-dev
spec:
  type: NodePort
  selector:
    app: dep-nginx
  ports:
    - port: 80
      nodePort: 30002
      targetPort: 80
